- id: poetry-dependencies-pinned
  name: Poetry dependencies pinned
  description: Ensure all poetry dependencies are pinned to exact versions
  entry: pin_poetry_dependencies.py
  language: python
  files: pyproject.toml
  additional_dependencies: [toml]
