name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 0 * * 1"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-poetry
        run: pipx install poetry
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml
          cache: poetry
      - name: install-dependencies
        run: poetry install --no-interaction --only dev
      - name: ruff-check
        run: poetry run ruff check .
      - name: ruff-format
        run: poetry run ruff format --check .
      - name: mypy
        run: poetry run mypy .
